apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "jmeter.fullname" . }}-slave
  {{- if .Values.annotations }}
  annotations:
    {{ toYaml .Values.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "jmeter.name" . }}-slave
    chart: {{ template "jmeter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.labels }}
  labels:
    {{ toYaml .Values.labels | indent 4 }}
  {{- end }}
spec:
  serviceName: {{ template "jmeter.fullname" . }}-slave
  replicas: {{ .Values.config.slaves.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "jmeter.name" . }}-slave
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "jmeter.name" . }}-slave
        release: {{ .Release.Name }}
    spec:
      hostAliases:
        - ip: 34.72.23.37
          hostnames:
            - gateway.am.axp.com
      containers:
        - name: {{ template "jmeter.name" . }}-slave
          image: "{{ .Values.images.slave.repo }}:{{ .Values.images.slave.tag }}"
          imagePullPolicy: {{ .Values.images.slave.pullPolicy }}
          env:
            - name: SSL_DISABLED
              value: "{{ .Values.config.disableSSL }}"
          livenessProbe:
            tcpSocket:
              port: 1099
            initialDelaySeconds: 60
            periodSeconds: 5
          ports:
            - containerPort: 1099
              name: server-port
              protocol: TCP
            - containerPort: 60001
              name: rmi-local-port
              protocol: TCP
          {{- if .Values.imageCredentials.pullSecrets }}
          imagePullSecrets:
            - name: {{ .Values.imageCredentials.pullSecrets }}
          {{- end }}
